[versions]
agp = "8.8.2"
lombok = "1.18.32"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }